//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class AlertTipsPanelView : UIView
{
  public Text txt_title;
  public Text txt_desc;
  public Button btn_confirm;

  public override void InitView()
  {
    base.InitView();
    txt_title = transform.Find("UITip/AlertTipsPanel/txt_title")?.GetComponent<Text>();
    txt_desc = transform.Find("UITip/AlertTipsPanel/txt_desc")?.GetComponent<Text>();
    btn_confirm = transform.Find("UITip/AlertTipsPanel/btn_confirm")?.GetComponent<Button>();
  }
}
