using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public class UIAutoGenerator : Editor
{
  // 自动生成代码存放的路径

  // 命名前缀与组件类型的映射字典
  private static readonly Dictionary<string, System.Type> PrefixToType = new Dictionary<string, System.Type>()
    {
        { "btn_", typeof(Button) },
        { "txt_", typeof(Text) },
        { "img_", typeof(Image) },
        { "obj_", typeof(GameObject) },
        { "tmp_", typeof(TMPro.TextMeshProUGUI) },
        { "slider_", typeof(Slider) },
        { "toggle_", typeof(Toggle) },
        { "input_", typeof(InputField) },
        { "scroll_", typeof(ScrollRect) },
        { "dropdown_", typeof(Dropdown) },
    };

  [MenuItem("GameObject/UI 工具/生成 UI View 并绑定代码", false, 0)]
  public static void GenerateUICode()
  {
    GameObject selectedObj = Selection.activeGameObject;
    if (selectedObj == null)
    {
      Debug.LogError("请先选中需要生成代码的 UI Prefab 或 Hierarchy 节点！");
      return;
    }

    string className = selectedObj.name + "View";
    List<BindInfo> bindInfos = new List<BindInfo>();

    // 1. 递归遍历 UI 节点，收集匹配的控件
    FindBindElements(selectedObj.transform, bindInfos);

    // 2. 拼接生成 C# 脚本字符串
    string codeStr = BuildCodeString(className, bindInfos);

    // 3. 写入文件
    CodeGenerationPaths.EnsureDirectoryExists(CodeGenerationPaths.UIGeneratedScriptsDirectory);

    string filePath = Path.Combine(CodeGenerationPaths.UIGeneratedScriptsDirectory, className + ".cs");
    File.WriteAllText(filePath, codeStr, Encoding.UTF8);

    AssetDatabase.Refresh();
    Debug.Log($"<color=green>UI 代码生成成功！路径: {filePath}</color>");
  }

  private static void FindBindElements(Transform target, List<BindInfo> bindInfos)
  {
    foreach (Transform child in target)
    {
      foreach (var kvp in PrefixToType)
      {
        if (child.name.StartsWith(kvp.Key))
        {
          bindInfos.Add(new BindInfo
          {
            FieldName = child.name,
            FieldType = kvp.Value,
            TransformPath = GetRelativePath(target.root, child)
          });
          break;
        }
      }

      // 递归遍历子节点
      if (child.childCount > 0)
      {
        FindBindElements(child, bindInfos);
      }
    }
  }

  private static string GetRelativePath(Transform root, Transform target)
  {
    if (root == target) return "";
    string path = target.name;
    Transform parent = target.parent;
    while (parent != null && parent != root)
    {
      path = parent.name + "/" + path;
      parent = parent.parent;
    }
    return path;
  }

  private static string BuildCodeString(string className, List<BindInfo> bindInfos)
  {
    StringBuilder sb = new StringBuilder();
    sb.AppendLine("//------------------------------------------------------------------------------");
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("//   此代码由 UI 工具自动生成，请勿手动修改！");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine("//------------------------------------------------------------------------------");
    sb.AppendLine("using UnityEngine;");
    sb.AppendLine("using UnityEngine.UI;");
    sb.AppendLine();
    sb.AppendLine("[RequireComponent(typeof(RectTransform))]");
    sb.AppendLine("[DisallowMultipleComponent]");
    sb.AppendLine($"public class {className} : UIView");
    sb.AppendLine("{");

    // 声明组件字段
    foreach (var info in bindInfos)
    {
      string typeName = info.FieldType == typeof(GameObject) ? "GameObject" : info.FieldType.Name;
      sb.AppendLine($"  public {typeName} {info.FieldName};");
    }

    sb.AppendLine();
    sb.AppendLine("  public override void InitView()");
    sb.AppendLine("  {");
    sb.AppendLine("    base.InitView();");

    // 自动查找并赋值代码 (即使不依赖拖拽，也可以在运行时自动 Bind)
    foreach (var info in bindInfos)
    {
      if (info.FieldType == typeof(GameObject))
      {
        sb.AppendLine($"    {info.FieldName} = transform.Find(\"{info.TransformPath}\")?.gameObject;");
      }
      else
      {
        sb.AppendLine($"    {info.FieldName} = transform.Find(\"{info.TransformPath}\")?.GetComponent<{info.FieldType.Name}>();");
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");

    return sb.ToString();
  }

  private class BindInfo
  {
    public string FieldName;
    public System.Type FieldType;
    public string TransformPath;
  }
}
