using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// UI 自动绑定工具
/// 一键生成View和Presenter，并在编译完成后自动挂载到Prefab上，同时为public字段或[SerializeField]字段自动赋值
/// </summary>
public class UIAutoBinder : Editor
{
  private const string PREFS_PENDING_KEY = "UI_AUTO_BIND_PENDING_DATA";

  /// <summary>控件命名前缀映射；同时支持 btnRestart 与 btn_Restart 两种命名。</summary>
  private static readonly PrefixBinding[] PrefixBindings =
  {
    new PrefixBinding("dropdown_", typeof(Dropdown)),
    new PrefixBinding("dropdown", typeof(Dropdown)),
    new PrefixBinding("slider_", typeof(Slider)),
    new PrefixBinding("slider", typeof(Slider)),
    new PrefixBinding("toggle_", typeof(Toggle)),
    new PrefixBinding("toggle", typeof(Toggle)),
    new PrefixBinding("scroll_", typeof(ScrollRect)),
    new PrefixBinding("scroll", typeof(ScrollRect)),
    new PrefixBinding("input_", typeof(InputField)),
    new PrefixBinding("input", typeof(InputField)),
    new PrefixBinding("btn_", typeof(Button)),
    new PrefixBinding("btn", typeof(Button)),
    // 项目 UI 文本统一使用 TMP_Text，避免生成代码依赖具体 TMP 实现。
    new PrefixBinding("txt_", typeof(TMPro.TMP_Text)),
    new PrefixBinding("txt", typeof(TMPro.TMP_Text)),
    new PrefixBinding("img_", typeof(Image)),
    new PrefixBinding("img", typeof(Image)),
    new PrefixBinding("obj_", typeof(GameObject)),
    new PrefixBinding("obj", typeof(GameObject)),
    new PrefixBinding("tmp_", typeof(TMPro.TMP_Text)),
    new PrefixBinding("tmp", typeof(TMPro.TMP_Text)),
  };

  #region 1. 菜单触发入口

  [MenuItem("GameObject/UI 工具/生成 UI View 与 Presenter 并自动绑定", false, 1)]
  public static void GenerateAndBindUI()
  {
    GameObject selectedObj = Selection.activeGameObject;
    if (selectedObj == null)
    {
      Debug.LogError("请选择要处理的 UI Prefab 节点！");
      return;
    }

    // 获取选中的 Asset 路径
    string prefabPath = AssetDatabase.GetAssetPath(selectedObj);
    if (string.IsNullOrEmpty(prefabPath))
    {
      Debug.LogError("请在 Project 窗口中选中 Prefab 资源文件（或选中的 Hierarchy 对象需为 Prefab 实例）！");
      return;
    }

    string baseName = selectedObj.name;
    string viewClassName = baseName + "View";
    string presenterClassName = baseName + "Presenter";

    // 收集节点绑定的信息
    List<BindElement> bindElements = new List<BindElement>();
    FindBindElements(selectedObj.transform, selectedObj.transform, bindElements);

    // 1. 生成 View 代码
    GenerateViewScript(viewClassName, bindElements);

    // 2. 生成 Presenter 逻辑代码模板 (防覆盖)
    GeneratePresenterScript(presenterClassName, viewClassName, bindElements);

    // 3. 存储延迟挂载任务数据
    PendingBindTask task = new PendingBindTask
    {
      PrefabPath = prefabPath,
      ViewClassName = viewClassName,
      Elements = bindElements
    };
    EditorPrefs.SetString(PREFS_PENDING_KEY, JsonUtility.ToJson(task));

    // 刷新 AssetDatabase 触发 Unity 编译
    AssetDatabase.Refresh();
    Debug.Log($"<color=yellow>[UI AutoBinder] 代码生成完毕，等待 Unity 编译后自动挂载组件...</color>");
  }

  /// <summary>仅生成带运行时查找逻辑的 View，不创建 Presenter，也不修改 Prefab。</summary>
  [MenuItem("GameObject/UI 工具/仅生成 UI View", false, 0)]
  public static void GenerateViewOnly()
  {
    GameObject selectedObj = Selection.activeGameObject;
    if (selectedObj == null)
    {
      Debug.LogError("请选择需要生成 View 的 UI Prefab 或 Hierarchy 节点。");
      return;
    }

    List<BindElement> bindElements = new List<BindElement>();
    FindBindElements(selectedObj.transform, selectedObj.transform, bindElements);
    string viewClassName = selectedObj.name + "View";
    GenerateViewScript(viewClassName, bindElements);
    AssetDatabase.Refresh();
    Debug.Log($"<color=green>[UI AutoBinder] 已生成 View：{viewClassName}</color>");
  }

  #endregion

  #region 2. 代码生成逻辑

  private static void GenerateViewScript(string className, List<BindElement> elements)
  {
    StringBuilder sb = new StringBuilder();
    sb.AppendLine("//------------------------------------------------------------------------------");
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("//   此代码由 UI 工具自动生成，请勿手动修改！");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine("//------------------------------------------------------------------------------");
    sb.AppendLine("using UnityEngine;");
    sb.AppendLine("using UnityEngine.UI;");
    if (elements.Exists(item => item.TypeName == nameof(TMPro.TMP_Text)))
      sb.AppendLine("using TMPro;");
    sb.AppendLine();
    sb.AppendLine("[RequireComponent(typeof(RectTransform))]");
    sb.AppendLine("[DisallowMultipleComponent]");
    sb.AppendLine($"public class {className} : UIView");
    sb.AppendLine("{");

    // 声明组件字段
    foreach (var item in elements)
    {
      string typeName = item.TypeName;
      sb.AppendLine($"  public {typeName} {item.FieldName};");
    }

    sb.AppendLine();
    sb.AppendLine("  public override void InitView()");
    sb.AppendLine("  {");
    sb.AppendLine("    base.InitView();");
    foreach (var item in elements)
    {
      if (item.TypeName == "GameObject")
        sb.AppendLine($"    {item.FieldName} = transform.Find(\"{item.RelativePath}\")?.gameObject;");
      else
        sb.AppendLine($"    {item.FieldName} = transform.Find(\"{item.RelativePath}\")?.GetComponent<{item.TypeName}>();");
    }
    sb.AppendLine("  }");
    sb.AppendLine("}");

    CodeGenerationPaths.EnsureDirectoryExists(CodeGenerationPaths.UIGeneratedScriptsDirectory);
    File.WriteAllText(Path.Combine(CodeGenerationPaths.UIGeneratedScriptsDirectory, className + ".cs"), sb.ToString(), Encoding.UTF8);
  }

  private static void GeneratePresenterScript(string presenterName, string viewName, List<BindElement> elements)
  {
    CodeGenerationPaths.EnsureDirectoryExists(CodeGenerationPaths.UIPresenterScriptsDirectory);
    string filePath = Path.Combine(CodeGenerationPaths.UIPresenterScriptsDirectory, presenterName + ".cs");

    // 核心机制：如果 Presenter 已存在，绝不覆盖写有业务逻辑的文件
    if (File.Exists(filePath))
    {
      Debug.Log($"[UI AutoBinder] {presenterName}.cs 已存在，跳过逻辑模板生成。");
      return;
    }

    StringBuilder sb = new StringBuilder();
    sb.AppendLine("using UnityEngine;");
    sb.AppendLine("using UnityEngine.UI;");
    sb.AppendLine();
    sb.AppendLine($"public class {presenterName} : BasePresenter");
    sb.AppendLine("{");
    sb.AppendLine($"  private {viewName} _view;");
    sb.AppendLine();
    sb.AppendLine("  public override void OnInit(UIView view)");
    sb.AppendLine("  {");
    sb.AppendLine("    base.OnInit(view);");
    sb.AppendLine($"    _view = view as {viewName};");
    sb.AppendLine();
    sb.AppendLine("    // 自动注册按钮事件绑定模板");

    foreach (var item in elements)
    {
      if (item.TypeName == "Button")
      {
        string callbackName = GetButtonCallbackName(item.FieldName);
        sb.AppendLine($"    _view.{item.FieldName}?.onClick.AddListener({callbackName});");
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine();
    sb.AppendLine("  public override void OnOpen(object args = null)");
    sb.AppendLine("  {");
    sb.AppendLine("    base.OnOpen(args);");
    sb.AppendLine("  }");
    sb.AppendLine();
    sb.AppendLine("  public override void OnClose()");
    sb.AppendLine("  {");
    sb.AppendLine("    base.OnClose();");
    sb.AppendLine("  }");
    sb.AppendLine();

    // 生成按钮响应事件桩函数
    foreach (var item in elements)
    {
      if (item.TypeName == "Button")
      {
        string callbackName = GetButtonCallbackName(item.FieldName);
        sb.AppendLine($"  private void {callbackName}()");
        sb.AppendLine("  {");
        sb.AppendLine($"    Debug.Log(\"{callbackName} Triggered!\");");
        sb.AppendLine("  }");
        sb.AppendLine();
      }
    }

    sb.AppendLine("}");

    File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
    Debug.Log($"<color=green>[UI AutoBinder] 业务模板已生成: {filePath}</color>");
  }

  #endregion

  #region 3. 编译完成后自动挂载与 SerializeField 自动赋值

  [DidReloadScripts]
  private static void OnScriptsReloaded()
  {
    if (!EditorPrefs.HasKey(PREFS_PENDING_KEY)) return;

    string json = EditorPrefs.GetString(PREFS_PENDING_KEY);
    EditorPrefs.DeleteKey(PREFS_PENDING_KEY);

    PendingBindTask task = JsonUtility.FromJson<PendingBindTask>(json);
    if (task == null) return;

    // 加载 Prefab 内容进行修改
    GameObject prefabGo = PrefabUtility.LoadPrefabContents(task.PrefabPath);
    if (prefabGo == null) return;

    // 获取新编译出来的 View 类型
    Type viewType = GetAssemblyType(task.ViewClassName);
    if (viewType == null)
    {
      Debug.LogError($"无法找到类型 {task.ViewClassName}，可能编译失败！");
      PrefabUtility.UnloadPrefabContents(prefabGo);
      return;
    }

    // 挂载或获取组件
    Component viewComp = prefabGo.GetComponent(viewType);
    if (viewComp == null)
    {
      viewComp = prefabGo.AddComponent(viewType);
    }

    // 使用 SerializedObject 来为 public / [SerializeField] 变量自动拖拽赋值
    SerializedObject so = new SerializedObject(viewComp);

    foreach (var elem in task.Elements)
    {
      SerializedProperty prop = so.FindProperty(elem.FieldName);
      if (prop == null) continue;

      Transform targetTrans = string.IsNullOrEmpty(elem.RelativePath)
          ? prefabGo.transform
          : prefabGo.transform.Find(elem.RelativePath);

      if (targetTrans == null) continue;

      if (elem.TypeName == "GameObject")
      {
        prop.objectReferenceValue = targetTrans.gameObject;
      }
      else
      {
        prop.objectReferenceValue = targetTrans.GetComponent(elem.TypeName);
      }
    }

    so.ApplyModifiedProperties();

    // 保存修改后的 Prefab
    PrefabUtility.SaveAsPrefabAsset(prefabGo, task.PrefabPath);
    PrefabUtility.UnloadPrefabContents(prefabGo);

    Debug.Log($"<color=green><b>[UI AutoBinder Success]</b> 已自动将 {task.ViewClassName} 挂载到 Prefab 并完成序列化字段绑定！</color>");
  }

  #endregion

  #region 辅助工具函数

  private static void FindBindElements(Transform root, Transform current, List<BindElement> list)
  {
    foreach (Transform child in current)
    {
      if (TryGetBindType(child, out Type componentType))
      {
        string path = GetRelativePath(root, child);
        list.Add(new BindElement
        {
          FieldName = child.name,
          TypeName = componentType == typeof(GameObject) ? "GameObject" : componentType.Name,
          RelativePath = path
        });
      }

      if (child.childCount > 0)
      {
        FindBindElements(root, child, list);
      }
    }
  }

  private static string GetRelativePath(Transform root, Transform target)
  {
    if (root == target) return "";
    string path = target.name;
    Transform parent = target.parent;
    while (parent != null && parent != root)
    {
      path = parent.name + "/" + path;
      parent = parent.parent;
    }
    return path;
  }

  /// <summary>
  /// 根据节点前缀确定控件类别。
  /// 项目 UI 文本统一使用 TMP_Text，因此 txt 与 tmp 前缀都会生成 TMP 字段。
  /// </summary>
  private static bool TryGetBindType(Transform target, out Type componentType)
  {
    foreach (PrefixBinding binding in PrefixBindings)
    {
      if (target.name.StartsWith(binding.Prefix, StringComparison.Ordinal))
      {
        componentType = binding.ComponentType;
        return true;
      }
    }

    componentType = null;
    return false;
  }

  private static Type GetAssemblyType(string typeName)
  {
    foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
    {
      Type type = assembly.GetType(typeName);
      if (type != null) return type;
    }
    return null;
  }

  private static string FirstCharToUpper(string input)
  {
    if (string.IsNullOrEmpty(input)) return input;
    return input[0].ToString().ToUpper() + input.Substring(1);
  }

  /// <summary>将 btnRestart 或 btn_Restart 转换为统一的 OnRestartClicked 回调名。</summary>
  private static string GetButtonCallbackName(string fieldName)
  {
    string actionName = fieldName;
    if (fieldName.StartsWith("btn_", StringComparison.Ordinal))
      actionName = fieldName.Substring("btn_".Length);
    else if (fieldName.StartsWith("btn", StringComparison.Ordinal))
      actionName = fieldName.Substring("btn".Length);

    return "On" + FirstCharToUpper(actionName) + "Clicked";
  }

  [Serializable]
  private class BindElement
  {
    public string FieldName;
    public string TypeName;
    public string RelativePath;
  }

  private readonly struct PrefixBinding
  {
    public readonly string Prefix;
    public readonly Type ComponentType;

    public PrefixBinding(string prefix, Type componentType)
    {
      Prefix = prefix;
      ComponentType = componentType;
    }
  }

  [Serializable]
  private class PendingBindTask
  {
    public string PrefabPath;
    public string ViewClassName;
    public List<BindElement> Elements;
  }

  #endregion
}
