//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class ConfirmPanelView : UIView
{
  public Image img_bg;
  public Text txt_title;
  public Text txt_desc;
  public Button btn_cancel;
  public Button btn_confirm;

  public override void InitView()
  {
    base.InitView();
    img_bg = transform.Find("ConfirmPanel/img_bg")?.GetComponent<Image>();
    txt_title = transform.Find("ConfirmPanel/Image/txt_title")?.GetComponent<Text>();
    txt_desc = transform.Find("ConfirmPanel/txt_desc")?.GetComponent<Text>();
    btn_cancel = transform.Find("ConfirmPanel/btn_cancel")?.GetComponent<Button>();
    btn_confirm = transform.Find("ConfirmPanel/btn_confirm")?.GetComponent<Button>();
  }
}
