//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class ConfirmPanel2View : UIView
{
  public Image img_bg;
  public Text txt_title;
  public Text txt_desc;
  public Button btn_cancel;
  public Button btn_confirm;
}
