//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TMPro;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class SurvivorHomeView : UIView
{
  public Button btnStart;
  public Image imgBg;
  public TMP_Text txtTmp;

  public override void InitView()
  {
    base.InitView();
    btnStart = transform.Find("btnStart")?.GetComponent<Button>();
    imgBg = transform.Find("btnStart/imgBg")?.GetComponent<Image>();
    txtTmp = transform.Find("btnStart/txtTmp")?.GetComponent<TMP_Text>();
  }
}
