//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TMPro;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class SurvivorMainView : UIView
{
  public Slider expSlider;
  public Text expLevelTxt;
  public Slider hpSlider;
  public Text hpValueText;

}
