//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using VampireSurvivorsLike;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class SurvivorSkillSelectPanelView : UIView
{
  public Button skill0;
  public Button skill1;
  public Button skill2;
  public Text timerText;
  public WeaponSO[] weapons;
}
