//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 UI 工具自动生成，请勿手动修改！
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TMPro;

[RequireComponent(typeof(RectTransform))]
[DisallowMultipleComponent]
public class SurvivorGameOverView : UIView
{
  public TMP_Text txtTitle;
  public TMP_Text txtInfo;
  public Button btnQuit;
  public Button btnRestart;

  public override void InitView()
  {
    base.InitView();
    txtTitle = transform.Find("txtTitle")?.GetComponent<TMP_Text>();
    txtInfo = transform.Find("txtInfo")?.GetComponent<TMP_Text>();
    btnQuit = transform.Find("btnQuit")?.GetComponent<Button>();
    btnRestart = transform.Find("btnRestart")?.GetComponent<Button>();
  }
}
